version: '3.9'
services:
  web_apache:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "Gruyere_app"
    environment:
      - DB_NAME=gruyere_app
      - DB_USER=root
      - DB_PASS=root
      - DB_HOST=127.0.0.1:3306
    ports:
      - 5500:80
    depends_on:
      - db
    volumes:
      - ./:/usr/src/gruyere_app
    command: bash -c "php -S 0.0.0.0:80 index.php"

  db:
    container_name: "Gruyere_App_Database"
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_USER: 'gruyere_app_user'
      MYSQL_DATABASE: 'gruyere_app'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - ./Config/Docker/mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    links:
      - db
    ports:
      - 7000:80